export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const REMOVE_MODEL = 'REMOVE_MODEL';
export const REMOVE_MANUFACTURER = 'REMOVE_MANUFACTURER';
export const REMOVE_PRODUCTION_YEAR = 'REMOVE_PRODUCTION_YEAR';
export const REMOVE_GAS = 'REMOVE_GAS';
export const REMOVE_CC = 'REMOVE_CC';
export const REMOVE_HORSE_POWER = 'REMOVE_HORSE_POWER';
// types for Add module
export const UPLOAD_MANUFACTURERS_LIST = 'UPLOAD_MANUFACTURERS_LIST';
export const ADD_MODEL = 'ADD_MODEL';
export const ADD_PRODUCTION_YEAR = 'ADD_PRODUCTION_YEAR';
export const ADD_SUB_TYPE = 'ADD_SUB_TYPE';
export const ADD_GAS = 'ADD_GAS';
export const ADD_GAS_ALL = 'ADD_GAS_ALL';
export const ADD_CC = 'ADD_CC';
export const ADD_HORSE_POWER = 'ADD_HORSE_POWER';
export const ADD_IMAGES = 'ADD_IMAGES'
// other
export const MANUFACTURER_SELECTED = 'MANUFACTURER_SELECTED';
// new 
export const UPLOAD_SLIDER_INDEX = 'UPLOAD_SLIDER_INDEX';
export const ADD_MANUFACTURER = 'ADD_MANUFACTURER';
export const CHANGE_MODAL0_STATE = 'CHANGE_MODAL0_STATE';
export const CHANGE_MODAL1_STATE = 'CHANGE_MODAL1_STATE';
export const CHANGE_MODAL2_STATE = 'CHANGE_MODAL2_STATE';
export const CHANGE_MODAL3_STATE = 'CHANGE_MODAL3_STATE';
export const UPLOAD_PRODUCTION_YEARS = 'UPLOAD_PRODUCTION_YEARS';
export const UPLOAD_MODEL = 'UPLOAD_MODEL';
export const UPLOAD_GAS = 'UPLOAD_GAS';
export const UPLOAD_CC = 'UPLOAD_CC';
export const UPLOAD_HP = 'UPLOAD_HP';
export const UPLOAD_MODELS = 'UPLOAD_MODELS';
export const UPLOAD_MAIN_MODAL_STATE = 'UPLOAD_MAIN_MODAL_STATE';
export const UPLOAD_IMG_ROW = 'UPLOAD_IMG_ROW';
export const SLIDER_ROW = 'SLIDER_ROW';
// search inputs
export const ADD_SEARCH_INPUT = 'ADD_SEARCH_INPUT';
export const ADD_SEARCH_INPUT_MANUFACTURER = 'ADD_SEARCH_INPUT_MANUFACTURER';
export const ADD_SEARCH_INPUT_MODEL = 'ADD_SEARCH_INPUT_MODEL';
export const ADD_SEARCH_INPUT_PRODUCTION_YEAR = 'ADD_SEARCH_INPUT_PRODUCTION_YEAR';
export const ADD_SEARCH_INPUT_GAS = 'ADD_SEARCH_INPUT_GAS';
export const ADD_SEARCH_INPUT_CC = 'ADD_SEARCH_INPUT_CC';
export const ADD_SEARCH_INPUT_HP = 'ADD_SEARCH_INPUT_HP';

// invoke search functions
export const INVOKE_INPUT_SEARCH = 'INVOKE_INPUT_SEARCH';
export const INVOKE_INPUT_SEARCH_MANUFACTURER = 'INVOKE_INPUT_SEARCH_MANUFACTURER';

